### ISSUE TITLE
Gamecube support

### ISSUE THREAD

**Issue by aceofstax** [heinermann/BOLTextract#3]
Hi,

I'm attempting to extract ROMs from "Namco Museum" which Mass Media Games developed. I tried using gba, n64, xbox and ps2 algorithms, but didn't have any luck extracting. 

I had to use the -b argument for BOLTextract to output anything at all, but I get primarily .unk files, with exception of one or two .unkimg files. cdi/dos/win algorithms do output files with this -b argument, but every file produced gets an error message about expected filesize. I wasn't expecting much with those older algorithms, but figured I'd test anyway.

I don't know if I can provide the Data0.blt file, but I'd be more than happy to test any changes to your code.

**Comment by heinermann** [comment]
It probably uses the n64 algo, not any of the others. Mass Media Games uses a proprietary file format for most of its media files so you'll have to figure those out from there. Rarely there are known files (the ones in [guess_type.cpp](https://github.com/heinermann/BOLTextract/blob/main/BOLT/bolt-extract/guess_type.cpp)) but otherwise the production of .unk files is correct. This tool only extracts the files and doesn't convert them.

**Comment by aceofstax** [comment]
I see. Then the files extracted are likely fine. 

For what it's worth, the boxart of the Gamecube version of Namco Museum is in the same style as the GBA edition. I would imagine the algorithm would be one already supported by BOLTextract. Or as you suggested, the N64 algorithm. It is a 2002 game, so it's within that 1999-2003 timeframe. 

Thanks for letting me know. Seems like if nothing else, BOLTextract is compatible with the GC release of Namco Museum.

I'm going to leave file hashes for Gamecube's Data0.blt here. If you would like me to provide anything else that could be useful (outside the files themselves) I can do that for you. For example, names sizes and hashes of the extracted content. It may be worth comparing to the Xbox and PS2 versions, which include the same lineup of games.

Else, feel free to close this issue. Thanks again 👍 

```
GC Namco Museum "Data0.blt" hashes
CRC32 = d6b131d9
MD5 = 10e704cf19d0e429d2a877edebeb9f5f
SHA1 = 99a42cc8c2b80ac64e51fc14e4e3940eefaa3701
```
